# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awscccli < Formula
  desc "Simple AWS CLI with Cloud Control API."
  homepage "https://github.com/chroju/awscccli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/awscccli/releases/download/v0.0.1/awscccli_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "1c06d8a6848a54a420a30c7926c54c4ee84e3bbe6e5b1414c90591f79b204879"

      def install
        bin.install "acc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chroju/awscccli/releases/download/v0.0.1/awscccli_0.0.1_Darwin_arm64.tar.gz"
      sha256 "2e7a0b4b92f2a5cfa3febc4c0769ba801073c6baf6a24d99aadeaac7c107fa3c"

      def install
        bin.install "acc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/awscccli/releases/download/v0.0.1/awscccli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "603046abaea2cae2f111f6d8c51e81da663587d1bfb8da5b1ff348627a5f03c4"

      def install
        bin.install "acc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chroju/awscccli/releases/download/v0.0.1/awscccli_0.0.1_Linux_arm64.tar.gz"
      sha256 "7f0c281828a1481f5e3fb254a9ce4c076b9fd261aee996c5dee7ca32c8077d88"

      def install
        bin.install "acc"
      end
    end
  end

  test do
    system "#{bin}/acc --version"
  end
end
