# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NatureRemoCli < Formula
  desc "Unofficial command line interface for Nature Remo."
  homepage "https://github.com/chroju/nature-remo-cli"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/chroju/nature-remo-cli/releases/download/v0.3.0/nature-remo-cli_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "e75d5d6eebd2ba3e086e8cbd904421c1c21a41fce3b8671090693cc729927bf6"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/chroju/nature-remo-cli/releases/download/v0.3.0/nature-remo-cli_0.3.0_Darwin_arm64.tar.gz"
    sha256 "ed96553cb80eaa6de7b56d15d9d07f07b99168f3aed2099ee6d8b8e9a9f998f8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/chroju/nature-remo-cli/releases/download/v0.3.0/nature-remo-cli_0.3.0_Linux_x86_64.tar.gz"
    sha256 "fa7eb2acceae1574e64db9579d6d4da8c700a1c33d8b193026cfa2c9ab3437ac"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/chroju/nature-remo-cli/releases/download/v0.3.0/nature-remo-cli_0.3.0_Linux_arm64.tar.gz"
    sha256 "528918d3f772a141b60cc2125402a2418c537fc73e34fed41aa8ecf30e13b364"
  end

  def install
    bin.install "remo"
  end

  test do
    system "#{bin}/remo --version"
  end
end
