# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parade < Formula
  desc "Parade is a simple CLI tool for AWS SSM parameter store."
  homepage "https://github.com/chroju/parade"
  version "0.3.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/chroju/parade/releases/download/v0.3.1/parade_0.3.1_Darwin_x86_64.tar.gz"
    sha256 "a5eac30961df57fe6d6ed0949524c7c2bd667caf6a4e7ea92271f0966d7cfce8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/chroju/parade/releases/download/v0.3.1/parade_0.3.1_Darwin_arm64.tar.gz"
    sha256 "ee505e50a28f655fa1a1750471294416732053131791f830aa369183a5988ebe"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/chroju/parade/releases/download/v0.3.1/parade_0.3.1_Linux_x86_64.tar.gz"
    sha256 "0613a68a438d3abbaf718ec162fab8e4c0102d54df1924b32c74f5b140503ac2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/chroju/parade/releases/download/v0.3.1/parade_0.3.1_Linux_arm64.tar.gz"
    sha256 "32a8d5b65b99bff5a1d689bfe101eef77fb0257a707dd9f3e9498825099c4c3a"
  end

  def install
    bin.install "parade"
  end

  test do
    system "#{bin}/parade --version"
  end
end
