# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcloud < Formula
  desc "Terraform Cloud CLI tool"
  homepage "https://github.com/chroju/tfcloud"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfcloud/releases/download/v0.2.2/tfcloud_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "e26bb8bf6ff6ec039910f78a2326d394baeb60ea2ef49d927d17abf6a4fb5ef7"

      def install
        bin.install "tfcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chroju/tfcloud/releases/download/v0.2.2/tfcloud_0.2.2_Darwin_arm64.tar.gz"
      sha256 "d8a9e8656d82233eb75ef60d28a5428793389d1550ea1fbe5f6ae9cbfffc5141"

      def install
        bin.install "tfcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfcloud/releases/download/v0.2.2/tfcloud_0.2.2_Linux_x86_64.tar.gz"
      sha256 "b71ffc1d1dae4d9a8cb5781f281f57c1820ad796fb3cf7d028fb30df24d38754"

      def install
        bin.install "tfcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chroju/tfcloud/releases/download/v0.2.2/tfcloud_0.2.2_Linux_arm64.tar.gz"
      sha256 "a92eacda5bc5fdfaf5862e466ea6ac94e0b4b8366f8f79d52e1fad602c24db11"

      def install
        bin.install "tfcloud"
      end
    end
  end

  test do
    system "#{bin}/tfcloud --version"
  end
end
