# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmodule < Formula
  desc "tfmodule is a CLI tool for managing Terraform modules."
  homepage "https://github.com/chroju/tfmodule"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "54d1b8c40a1763506b6178f24206851a08c168df1dc4a7a50fda2ceb6776f369"

      def install
        bin.install "tfmodule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Darwin_arm64.tar.gz"
      sha256 "c027410a06c88f38635e4c1a6060e75b5d34d10e0ba27226b42d61b42aef9770"

      def install
        bin.install "tfmodule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Linux_arm64.tar.gz"
      sha256 "86c6acf4efb1d48af17015c71353132693e24460fd3689bf71537aa5c5587b4a"

      def install
        bin.install "tfmodule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Linux_x86_64.tar.gz"
      sha256 "820e32c327c68c1bb3b7fe1b156f2dd9f83c812838e5fab87af28709038c0e12"

      def install
        bin.install "tfmodule"
      end
    end
  end

  test do
    system "#{bin}/tfmodule --version"
  end
end
