# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmodule < Formula
  desc "tfmodule is a CLI tool for managing Terraform modules."
  homepage "https://github.com/chroju/tfmodule"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "431252705ec0c664fdbe515ad3b54300d8badad32091e7a8237c68ad00ea7878"

      def install
        bin.install "tfmodule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Darwin_arm64.tar.gz"
      sha256 "723e503203c0a1535e815cc4b5fbf6f40dcc7c4fad1dfe95b34ef57b8673b936"

      def install
        bin.install "tfmodule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Linux_arm64.tar.gz"
      sha256 "49c314b67cab4f359e7dfe9bf7f3fcb92d9076fbfec0d6218dcbaf9f9789655c"

      def install
        bin.install "tfmodule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chroju/tfmodule/releases/download/v0.1.1/tfmodule_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ef0e95365786780c49346974f7db28f93c3446eb56f1080c9a3c4070f54b9a10"

      def install
        bin.install "tfmodule"
      end
    end
  end

  test do
    system "#{bin}/tfmodule --version"
  end
end
